[package]
name = "ferrum"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "*", features = ["full"] }
crossterm = "0.28.1"
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
bitflags = "1.2.1"
sdl2 = "0.37.0"
rand = "=0.7.3"
